plugins {
    id 'java-library'
    id("io.qameta.allure") version "4.1.0"
}

repositories {
    mavenCentral()
}

allure {
    version.set("2.46.0")
}

group = 'guru.qa'
version = '1.0-SNAPSHOT'

dependencies {
    testImplementation (
            "com.codeborne:selenide:7.16.0",
            "org.junit.jupiter:junit-jupiter:5.14.2",
            "com.github.javafaker:javafaker:1.0.2",
            "io.qameta.allure:allure-selenide:2.35.4")
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    constraints {
        ("org.seleniumhq.selenium:selenium-java:4.45.0")
        ("org.seleniumhq.selenium:selenium-chrome-driver:4.45.0")
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test) {
    useJUnitPlatform()
    systemProperties(System.getProperties())
    ignoreFailures = true

    testLogging {
        lifecycle {
            events  = ["started", "skipped", "failed", "standard_error", "standard_out"]
            exceptionFormat = "short"
        }
    }
}