plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation (
            "com.codeborne:selenide:7.16.0",
            "org.junit.jupiter:junit-jupiter:5.14.2" )
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.9.3'

    // Принудительно поднимаем версию Selenium для Selenide
    constraints {
        testImplementation('org.seleniumhq.selenium:selenium-java:4.45.0')
        testImplementation('org.seleniumhq.selenium:selenium-chrome-driver:4.45.0')
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}
